server:
  port: 8089

spring:
  # spring-session 使用
  session:
    store-type: none

  # mysql配置
  datasource:
    url: jdbc:mysql://cdb-7qcsgxvo.cd.tencentcdb.com:10067/mojito_learn?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lfq12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 175.24.93.154
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 5

mybatis:
  type-aliases-package: com.charles.learn.mybatis #指定bean所在包
  mapperLocations: classpath:mapper/*.xml #指定映射文件

rocketmq:
  name-server: 116.62.9.135:9876
  producer:
    group: my-group
